name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Clean Binaries
      run: make clean -s

    - name: Build Binaries
      run: make -s

    - name: Compile Tests
      run: for i in ../tests/*.qas; do ./bin/quarki -f "$i"; done
